name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build and test
      run: |
        npm ci
        npm test
        
    - name: Build Docker image
      run: docker build -t linkbio-api .
      
    - name: Deploy to production
      if: success()
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        export KUBECONFIG=./kubeconfig
        kubectl apply -f kubernetes/